/**
 * Regenerates web/src/biomes.ts from the vendored vanilla biome registry.
 *
 * The registry itself lives in tools/vanilla/minecraft/biome_registry.json so
 * the build never needs the network. Refresh it with --fetch, which reads the
 * 26.2-registries and 26.2-data tags of misode/mcmeta — the same source the
 * rest of the vendored vanilla data comes from. Grouping follows the
 * #minecraft:is_overworld / is_nether / is_end tags rather than a hand-kept
 * list, so a biome cannot end up in the wrong dimension.
 *
 * Run with: npm run biomes [-- --fetch]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const WEB = join(dirname(fileURLToPath(import.meta.url)), "..");
const REGISTRY = join(WEB, "..", "tools", "vanilla", "minecraft", "biome_registry.json");
const OUT = join(WEB, "src", "biomes.ts");
const VERSION = "26.2";

async function fetchRegistry() {
  const base = "https://raw.githubusercontent.com/misode/mcmeta";
  const json = async (url) => {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    return response.json();
  };
  const all = await json(`${base}/${VERSION}-registries/worldgen/biome/data.json`);
  const tag = async (name) =>
    (await json(`${base}/${VERSION}-data/data/minecraft/tags/worldgen/biome/${name}.json`)).values.map((id) =>
      id.replace(/^minecraft:/, ""),
    );
  const [overworld, nether, end] = await Promise.all([tag("is_overworld"), tag("is_nether"), tag("is_end")]);
  const claimed = new Set([...overworld, ...nether, ...end]);
  return {
    _comment:
      `Vanilla biome registry for Minecraft ${VERSION}, from the ${VERSION}-registries and ` +
      `${VERSION}-data tags of misode/mcmeta. Grouped by the #minecraft:is_overworld / ` +
      "is_nether / is_end biome tags; anything in none of them lands in 'other'.",
    minecraft_version: VERSION,
    overworld: [...overworld].sort(),
    nether: [...nether].sort(),
    end: [...end].sort(),
    other: all.filter((id) => !claimed.has(id)).sort(),
  };
}

if (process.argv.includes("--fetch")) {
  const fresh = await fetchRegistry();
  writeFileSync(REGISTRY, `${JSON.stringify(fresh, null, 2)}\n`);
  console.log(`refreshed ${REGISTRY}`);
}

const registry = JSON.parse(readFileSync(REGISTRY, "utf8"));
const groups = ["overworld", "nether", "end", "other"];
const total = groups.reduce((sum, key) => sum + registry[key].length, 0);

const list = (key) =>
  registry[key].map((id) => `  "minecraft:${id}",`).join("\n");

writeFileSync(
  OUT,
  `/**
 * Every biome in the vanilla Minecraft ${registry.minecraft_version} registry, grouped by the
 * dimension tag that claims it.
 *
 * Generated by web/tools/biome-list.mjs from
 * tools/vanilla/minecraft/biome_registry.json — do not edit by hand.
 *
 * Registry ids are never translated: they are what the data pack writes and
 * what a player searches for in the game.
 */

export interface BiomeGroup {
  /** Translation key for the group heading. */
  key: string;
  biomes: string[];
}

/** Biomes the Overworld biome source can place. */
export const VANILLA_OVERWORLD_BIOMES: string[] = [
${list("overworld")}
];

export const VANILLA_NETHER_BIOMES: string[] = [
${list("nether")}
];

export const VANILLA_END_BIOMES: string[] = [
${list("end")}
];

/** In the registry but in no dimension tag. */
export const VANILLA_OTHER_BIOMES: string[] = [
${list("other")}
];

/**
 * All ${total} of them, in the order the biome brush lists them. The Overworld
 * comes first because that is what the brush is for; the rest are offered
 * because the layer can hold any biome id and refusing to show one would be an
 * arbitrary limit.
 */
export const BIOME_GROUPS: BiomeGroup[] = [
  { key: "biomeGroup.overworld", biomes: VANILLA_OVERWORLD_BIOMES },
  { key: "biomeGroup.nether", biomes: VANILLA_NETHER_BIOMES },
  { key: "biomeGroup.end", biomes: VANILLA_END_BIOMES },
  { key: "biomeGroup.other", biomes: VANILLA_OTHER_BIOMES },
];

export const ALL_VANILLA_BIOMES: string[] = BIOME_GROUPS.flatMap((group) => group.biomes);
`,
);
console.log(`${total} biomes written to web/src/biomes.ts`);
