/**
 * Every biome in the vanilla Minecraft 26.2 registry, grouped by the
 * dimension tag that claims it.
 *
 * Generated by web/tools/biome-list.mjs from
 * tools/vanilla/minecraft/biome_registry.json — do not edit by hand.
 *
 * Registry ids are never translated: they are what the data pack writes and
 * what a player searches for in the game.
 */

export interface BiomeGroup {
  /** Translation key for the group heading. */
  key: string;
  biomes: string[];
}

/** Biomes the Overworld biome source can place. */
export const VANILLA_OVERWORLD_BIOMES: string[] = [
  "minecraft:badlands",
  "minecraft:bamboo_jungle",
  "minecraft:beach",
  "minecraft:birch_forest",
  "minecraft:cherry_grove",
  "minecraft:cold_ocean",
  "minecraft:dark_forest",
  "minecraft:deep_cold_ocean",
  "minecraft:deep_dark",
  "minecraft:deep_frozen_ocean",
  "minecraft:deep_lukewarm_ocean",
  "minecraft:deep_ocean",
  "minecraft:desert",
  "minecraft:dripstone_caves",
  "minecraft:eroded_badlands",
  "minecraft:flower_forest",
  "minecraft:forest",
  "minecraft:frozen_ocean",
  "minecraft:frozen_peaks",
  "minecraft:frozen_river",
  "minecraft:grove",
  "minecraft:ice_spikes",
  "minecraft:jagged_peaks",
  "minecraft:jungle",
  "minecraft:lukewarm_ocean",
  "minecraft:lush_caves",
  "minecraft:mangrove_swamp",
  "minecraft:meadow",
  "minecraft:mushroom_fields",
  "minecraft:ocean",
  "minecraft:old_growth_birch_forest",
  "minecraft:old_growth_pine_taiga",
  "minecraft:old_growth_spruce_taiga",
  "minecraft:pale_garden",
  "minecraft:plains",
  "minecraft:river",
  "minecraft:savanna",
  "minecraft:savanna_plateau",
  "minecraft:snowy_beach",
  "minecraft:snowy_plains",
  "minecraft:snowy_slopes",
  "minecraft:snowy_taiga",
  "minecraft:sparse_jungle",
  "minecraft:stony_peaks",
  "minecraft:stony_shore",
  "minecraft:sulfur_caves",
  "minecraft:sunflower_plains",
  "minecraft:swamp",
  "minecraft:taiga",
  "minecraft:warm_ocean",
  "minecraft:windswept_forest",
  "minecraft:windswept_gravelly_hills",
  "minecraft:windswept_hills",
  "minecraft:windswept_savanna",
  "minecraft:wooded_badlands",
];

export const VANILLA_NETHER_BIOMES: string[] = [
  "minecraft:basalt_deltas",
  "minecraft:crimson_forest",
  "minecraft:nether_wastes",
  "minecraft:soul_sand_valley",
  "minecraft:warped_forest",
];

export const VANILLA_END_BIOMES: string[] = [
  "minecraft:end_barrens",
  "minecraft:end_highlands",
  "minecraft:end_midlands",
  "minecraft:small_end_islands",
  "minecraft:the_end",
];

/** In the registry but in no dimension tag. */
export const VANILLA_OTHER_BIOMES: string[] = [
  "minecraft:the_void",
];

/**
 * All 66 of them, in the order the biome brush lists them. The Overworld
 * comes first because that is what the brush is for; the rest are offered
 * because the layer can hold any biome id and refusing to show one would be an
 * arbitrary limit.
 */
export const BIOME_GROUPS: BiomeGroup[] = [
  { key: "biomeGroup.overworld", biomes: VANILLA_OVERWORLD_BIOMES },
  { key: "biomeGroup.nether", biomes: VANILLA_NETHER_BIOMES },
  { key: "biomeGroup.end", biomes: VANILLA_END_BIOMES },
  { key: "biomeGroup.other", biomes: VANILLA_OTHER_BIOMES },
];

export const ALL_VANILLA_BIOMES: string[] = BIOME_GROUPS.flatMap((group) => group.biomes);
